car_with_arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_joint1
    pid: {p: 100, i: 0.0005, d: 0.05}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_joint2
    pid: {p: 100, i: 0.0005, d: 0.05}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_joint3
    pid: {p: 100, i: 0.0005, d: 0.05}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_joint4
    pid: {p: 100, i: 0.0005, d: 0.05}

  # Effort Controllers
  grip1_effort_controller:
    type: effort_controllers/JointPositionController
    joint: grip_joint1
    pid: {p: 1.0, i: 0.0, d: 0.0}

  grip2_effort_controller:
    type: effort_controllers/JointPositionController
    joint: grip_joint2
    pid: {p: 1.0, i: 0.0, d: 0.0}
